import Header from "../../header/header";
import DetailNews from "./detailNews";
import DetailPromotionNews from "./detailPromotionNews";
import { redirect } from "next/navigation";
import { hostApi } from "../../lib/config";
import "../../../../public/css/cssNews.css";
import Footer from "../../../components/footer";

async function fetchNewsDetail(slug) {
  const { slugDetailNews } = slug;

  try {
    const response = await fetch(
      `${hostApi}/member/news-detail/${slugDetailNews[0]}/${slugDetailNews[1]}`,
      {
        method: "GET",
      }
    );
    if (!response.ok) {
      throw new Error("Network response was not ok");
    }

    const data = await response.json();

    if (!data.status || !data.data) {
      redirect("/");
    }
    return data.data;
  } catch (error) {
    redirect("/");

    console.error("Fetch error: ", error);
  }
}

export const metadata = {
  title: "Tin khuyến mãi",
  description: "Generated by Next.js",
};

async function fetchNewsRelated(slug) {
  const { slugDetailNews } = slug;

  if (slugDetailNews[0] === "tin-khuyen-mai") {
    return [];
  }

  try {
    const response = await fetch(
      `${hostApi}/member/related-new/${slugDetailNews[0]}/${slugDetailNews[1]}`,
      {
        method: "GET",
      }
    );

    if (!response.ok) {
      throw new Error("Network response was not ok");
    }

    const data = await response.json();
    return data.relatedNew;
  } catch (error) {
    console.error("Fetch error: ", error);
    return [];
  }
}

const HomePage = async ({ params }) => {
  const { slugDetailNews } = params;

  const dataNewsDetail = await fetchNewsDetail(params);
  let dataRelatedNews = [];

  if (slugDetailNews[0] !== "tin-khuyen-mai") {
    dataRelatedNews = await fetchNewsRelated(params);
  }

  return (
    <div className="container-fluid px-0">
      <Header />
      {slugDetailNews[0] !== "tin-khuyen-mai" ? (
        <DetailNews
          dataRelatedNews={dataRelatedNews}
          dataNewsDetail={dataNewsDetail || []}
        />
      ) : (
        <DetailPromotionNews data={dataNewsDetail || []} />
      )}

      <Footer />
    </div>
  );
};

export default HomePage;
