import React from "react";
import Header from "../../header/header";
import "../../../../public/css/cssAccount.css";
import ContentViewedProducts from "./contentViewedProducts";
export const metadata = {
  title: "Sản phẩm đã xem",
  description: "Generated by Next.js",
};

const Account = () => {
  return (
    <div className="container-fluid px-0">
      <Header />
      <ContentViewedProducts />
    </div>
  );
};

export default Account;
