import React from "react";
import Header from "../header/header";
import Footer from "../../components/footer";

import "../../../public/css/cssAccount.css";
import ContentAccount from "./contentAccount";

export const metadata = {
  title: "Thông tin tài khoản",
  description: "Generated by Next.js",
};

const Account = () => {
  return (
    <div className="container-fluid px-0">
      <Header />
      <ContentAccount />
      <Footer />
    </div>
  );
};

export default Account;
